### PR TITLE
Add parameter to always use 4-byte start codes before NAL units

### PR DESCRIPTION
**Pull request by SCG82**
(needed for WebRTC bitstream parser)

### CODE REVIEW

**Comment by MasterNobody** [comment]
Can you point me to which part of WebRTC spec say that it need 4-byte start codes?

**Comment by SCG82** [comment]
https://webrtc.googlesource.com/src/+/refs/heads/master/modules/video_coding/jitter_buffer_common.h

`enum { kH264StartCodeLengthBytes = 4 };

https://webrtc.googlesource.com/src/+/refs/heads/master/modules/video_coding/codecs/h264/h264_encoder_impl.cc#96

`Each NAL unit is a fragment starting with the four-byte start code {0,0,0,1}`

**Comment by MasterNobody** [comment]
I have said specs, not source code of Chrome part for encoder and not for decoder. Also what about Firefox? AFAIK WebRTC is protocol and not the only Google implementation which can have bugs which others should mimic/workaround them. Do they have some protocol documents for codecs which can be used and which feautures they can use?

**Comment by SCG82** [comment]
I'm fairly certain there is no such requirement in the WebRTC specs (https://tools.ietf.org/html/rfc7742). However, the webrtc.org implementation is a _de facto_ standard which assumes H264 NAL start codes are `00 00 00 01`. This proposed addition to x264 will make it easier for others to use with the webrtc.org codebase without having to iterate through each NAL unit and prepend `00` to all 3-byte start codes.

**Comment by MasterNobody** [comment]
As far as I read in https://tools.ietf.org/html/rfc7742#section-6.2 payload formats is defined in RFC6184 which in https://tools.ietf.org/html/rfc6184#section-1.1 specifically says that "In the scope of this memo, Annex B is not relevant." and in https://tools.ietf.org/html/rfc6184#section-1.3 it says that " This payload specification can only be used to carry the "naked" H.264 NAL unit stream over RTP and not the bitstream format discussed in Annex B of H.264.".

So IMHO you shouldn't use Annex B in first place i.e. you should set `param->b_annexb = 0;` and than you wouldn't care if start codes where short or long for parsing of encoded NAL (you will get 4-byte size instead of start codes).

**Pull request closed without merging**
